// @ts-check
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';
import astroD2 from 'astro-d2';
import starlightFullViewMode from 'starlight-fullview-mode';
import starlightLinksValidator from 'starlight-links-validator';
import react from '@astrojs/react';
import icon from 'astro-icon';

// Filesystem-driven sidebar: every top-level folder under src/content/docs/
// becomes an autogenerated group. Drop a new folder in and it shows up on
// the next dev-server start — no config edits required.
const docsDir = join(dirname(fileURLToPath(import.meta.url)), 'src/content/docs');

// Folder names carry a 3-digit chapter prefix (e.g. "004 The first project
// scaffold") so the filesystem and Starlight's sort both order by chapter.
// The prefix is stripped from the sidebar label so the UI stays clean.
const sidebarGroups = readdirSync(docsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .sort()
    .map((name) => ({
        label: name.replace(/^\d+\s+/, ''),
        items: [{ autogenerate: { directory: name } }],
    }));
// Expressive Code options live in ./ec.config.mjs so the standalone
// astro-expressive-code <Code> component can load them (it requires a
// dedicated config file because EC plugins are function values).

// https://astro.build/config
export default defineConfig({
    // PGlite ships its Postgres WASM and a ~5 MB filesystem data blob as
    // package-internal assets; Vite's dep optimizer mangles those paths and
    // the FS bundle ends up being served as HTML. Exclude PGlite from the
    // optimizer so its own asset resolution kicks in.
    //
    // `worker.format: 'es'` is needed for the DrizzleCoding component — its
    // worker imports drizzle-orm which Rollup code-splits across multiple
    // chunks, and Vite's default IIFE worker format can't represent that
    // graph. ES-module workers can.
    vite: {
        optimizeDeps: {
            exclude: ['@electric-sql/pglite'],
        },
        worker: {
            format: 'es',
        },
        plugins: [
            // Site-wide cross-origin isolation.
            //
            // StackBlitz's WebContainer is built on SharedArrayBuffer, which
            // browsers only expose in cross-origin isolated documents. Agent
            // clusters are inherited from the top-level browsing context, so
            // an iframe can only be isolated if the embedding lesson page is
            // isolated too — there is no per-iframe escape hatch.
            //
            // The trade-off is on the *other* cross-origin iframes the site
            // embeds (YouTube nocookie, Tailwind play, TS playground, etc.):
            // they must either send COEP themselves (StackBlitz does) or be
            // tagged `<iframe credentialless>` so they load without
            // credentials. That tag lives on the two iframe-renderers in the
            // codebase — SandboxCallout and VideoCallout.
            //
            // Production: see public/_headers (Netlify, Cloudflare Pages).
            // For Vercel, equivalent rules go in vercel.json under "headers".
            {
                name: 'coop-coep-site-wide',
                configureServer(server) {
                    server.middlewares.use((req, res, next) => {
                        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
                        res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless');
                        next();
                    });
                },
                configurePreviewServer(server) {
                    server.middlewares.use((req, res, next) => {
                        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
                        res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless');
                        next();
                    });
                },
            },
        ],
    },
    integrations: [
        icon(),
        mermaid({ autoTheme: true }),
        astroD2({
            // Use the WASM build (D2.js) so contributors don't need the D2 CLI installed.
            // `inline: true` is required when useD2js is on for icons/themes to apply.
            experimental: { useD2js: true },
            inline: true,
            layout: 'elk',
            theme: { default: '0', dark: '200' },
        }),
        starlight({
        title: 'LEARN REACT SAAS',
        customCss: ['./src/styles/custom.css'],
        plugins: [starlightFullViewMode({}), starlightLinksValidator()],
        components: {
            // Renders LessonEyebrow above the default H1 on every page,
            // reading chapter-id, chapter-title, and sidebar.order from
            // the lesson's frontmatter.
            PageTitle: './src/components/overrides/PageTitle.astro',
            // Adds the React-inspired orbit mark + three-tone wordmark
            // to the header, replacing Starlight's plain-text title.
            SiteTitle: './src/components/overrides/SiteTitle.astro',
        },
        head: [
            {
                // Default starlight-fullview-mode's right sidebar to *collapsed*
                // on laptop-width viewports (< 100rem ≈ 1600px). The plugin
                // reads sessionStorage.rightSideBarCollapsed on DOMContentLoaded;
                // seeding it here (before the plugin runs) overrides its
                // expanded-by-default. Only seed when the user hasn't toggled
                // yet this session, so a manual click still sticks.
                tag: 'script',
                content: `(function () {
try {
    if (sessionStorage.getItem('rightSideBarCollapsed') !== null) return;
    if (window.matchMedia('(max-width: 99.999rem)').matches) {
        sessionStorage.setItem('rightSideBarCollapsed', 'true');
    }
} catch (e) {}
})();`,
            },
            {
                tag: 'script',
                content: `(function () {
var path = location.pathname;
var isRoot = path === '/' || path === '/index.html';
// ?home=1 from the site-title click opts out of the lastLesson bounce
// so the index page is reachable.
var wantsHome = location.search.indexOf('home=1') !== -1;
// Synchronous redirect from / — runs before paint, no flash.
if (isRoot && !wantsHome) {
		var last = localStorage.getItem('lastLesson');
		if (last && last.charAt(0) === '/' && last.charAt(1) !== '/' && last !== path) {
        location.replace(last);
        return;
		}
}
// Defer save/heal until <title> is parsed so we can detect 404 pages.
document.addEventListener('DOMContentLoaded', function () {
		var is404 = /^404\\b/.test(document.title);
		if (is404) {
        // If the saved lesson is what landed us on this 404, clear it
        // and bounce home so we don't strand the user on a dead page.
        if (localStorage.getItem('lastLesson') === path) {
            localStorage.removeItem('lastLesson');
            location.replace('/');
        }
        return;
		}
		if (!isRoot) {
        try { localStorage.setItem('lastLesson', path); } catch (e) {}
		}
});
})();`,
            },
            {
                // Per-lesson "finished" dots in the left sidebar. A lesson is
                // marked finished once the bottom pagination block has been
                // continuously visible for >= 2s — captures "scrolled to the
                // end and lingered" without false positives from a quick open.
                // State is per-browser localStorage; the matching CSS lives in
                // src/styles/custom.css under nav.sidebar a[data-finished].
                tag: 'script',
                content: `(function () {
var KEY = 'finishedLessons';
function readSet() {
    try {
        var raw = localStorage.getItem(KEY);
        var arr = raw ? JSON.parse(raw) : [];
        return new Set(Array.isArray(arr) ? arr : []);
    } catch (e) { return new Set(); }
}
function paint(set) {
    var links = document.querySelectorAll('nav.sidebar a[href]');
    for (var i = 0; i < links.length; i++) {
        if (set.has(links[i].pathname)) {
            links[i].setAttribute('data-finished', '');
        }
    }
}
document.addEventListener('DOMContentLoaded', function () {
    if (/^404\\b/.test(document.title)) return;
    var finished = readSet();
    paint(finished);
    var path = location.pathname;
    if (finished.has(path)) return;
    var pagination = document.querySelector('.pagination-links');
    if (!pagination) return;
    var timer = null;
    var observer = new IntersectionObserver(function (entries) {
        for (var i = 0; i < entries.length; i++) {
            if (entries[i].isIntersecting) {
                if (timer === null) {
                    timer = setTimeout(function () {
                        finished.add(path);
                        try { localStorage.setItem(KEY, JSON.stringify(Array.from(finished))); } catch (e) {}
                        paint(finished);
                        observer.disconnect();
                    }, 2000);
                }
            } else if (timer !== null) {
                clearTimeout(timer);
                timer = null;
            }
        }
    });
    observer.observe(pagination);
});
})();`,
            },
        ],
        sidebar: sidebarGroups,
        }),
        react(),
    ],
});